

-- Tablas de Conductor

SELECT * FROM CONDUCTOR WHERE ID_CONDUCTOR=ID_CONDUCTOR;
SELECT * FROM CONDUCTOR;
INSERT INTO CONDUCTOR (ID_CONDUCTOR,ID_PERSONA) VALUES (ID_CONDUCTOR,ID_PERSONA);
UPDATE CONDUCTOR SET ID_CONDUCTOR=ID_CONDUCTOR,ID_PERSONA=ID_PERSONA WHERE ID_CONDUCTOR=ID_CONDUCTOR;
DELETE * FROM CONDUCTOR WHERE ID_CONDUCTOR=ID_CONDUCTOR;



-- PROCEDIMIENTOS --

CREATE OR REPLACE PROCEDURE proc_insert_conductor(v_id_conductor NUMBER,v_id_persona NUMBER)
AS 
BEGIN 
INSERT INTO Conductor (ID_CONDUCTOR,ID_PERSONA) VALUES (v_id_conductor,v_id_persona);    
END;

