

-- Tablas de Departamento

SELECT * FROM DEPARTAMENTO WHERE ID_DEPARTAMENTO=ID_DEPARTAMENTO;
SELECT * FROM DEPARTAMENTO;
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO,DIRECCION,ID_COMUNA,HABITACIONES,CAPACIDAD,PRECIO,AMUEBLADO,CABLE,INTERNET,CALEFACCION,DESCRIPCION) VALUES (ID_DEPARTAMENTO,"DIRECCION",ID_COMUNA,HABITACIONES,CAPACIDAD,PRECIO,"AMUEBLADO","CABLE","INTERNET","CALEFACCION","DESCRIPCION");
UPDATE DEPARTAMENTO SET ID_DEPARTAMENTO=ID_DEPARTAMENTO,DIRECCION="DIRECCION",ID_COMUNA=ID_COMUNA,HABITACIONES=HABITACIONES,CAPACIDAD=CAPACIDAD,PRECIO=PRECIO,AMUEBLADO="AMUEBLADO",CABLE="CABLE",INTERNET="INTERNET",CALEFACCION="CALEFACCION",DESCRIPCION="DESCRIPCION" WHERE ID_DEPARTAMENTO=ID_DEPARTAMENTO;
DELETE * FROM DEPARTAMENTO WHERE ID_DEPARTAMENTO=ID_DEPARTAMENTO;



-- PROCEDIMIENTOS --

CREATE OR REPLACE PROCEDURE proc_insert_departamento(v_id_departamento NUMBER,v_direccion VARCHAR2,v_id_comuna NUMBER,v_habitaciones NUMBER,v_capacidad NUMBER,v_precio NUMBER,v_amueblado CHAR,v_cable CHAR,v_internet CHAR,v_calefaccion CHAR,v_descripcion VARCHAR2)
AS 
BEGIN 
INSERT INTO Departamento (ID_DEPARTAMENTO,DIRECCION,ID_COMUNA,HABITACIONES,CAPACIDAD,PRECIO,AMUEBLADO,CABLE,INTERNET,CALEFACCION,DESCRIPCION) VALUES (v_id_departamento,v_direccion,v_id_comuna,v_habitaciones,v_capacidad,v_precio,v_amueblado,v_cable,v_internet,v_calefaccion,v_descripcion);    
END;

