

-- Tablas de Departments

SELECT * FROM DEPARTMENTS WHERE DEPARTMENT_ID=DEPARTMENT_ID;
SELECT * FROM DEPARTMENTS;
INSERT INTO DEPARTMENTS (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,LOCATION_ID) VALUES (DEPARTMENT_ID,"DEPARTMENT_NAME",MANAGER_ID,LOCATION_ID);
UPDATE DEPARTMENTS SET DEPARTMENT_ID=DEPARTMENT_ID,DEPARTMENT_NAME="DEPARTMENT_NAME",MANAGER_ID=MANAGER_ID,LOCATION_ID=LOCATION_ID WHERE DEPARTMENT_ID=DEPARTMENT_ID;
DELETE * FROM DEPARTMENTS WHERE DEPARTMENT_ID=DEPARTMENT_ID;



-- PROCEDIMIENTOS --

CREATE OR REPLACE PROCEDURE proc_insert_departments(v_department_id NUMBER,v_department_name VARCHAR2,v_manager_id NUMBER,v_location_id NUMBER)
AS 
BEGIN 
INSERT INTO Departments (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,LOCATION_ID) VALUES (v_department_id,v_department_name,v_manager_id,v_location_id);    
END;

