

-- Tablas de Inventario

SELECT * FROM INVENTARIO WHERE ID_INVENTARIO=ID_INVENTARIO;
SELECT * FROM INVENTARIO;
INSERT INTO INVENTARIO (ID_INVENTARIO,ID_DEPARTAMENTO,NOMBRE,DESCRIPCION,CANTIDAD,VALOR) VALUES (ID_INVENTARIO,ID_DEPARTAMENTO,"NOMBRE","DESCRIPCION",CANTIDAD,VALOR);
UPDATE INVENTARIO SET ID_INVENTARIO=ID_INVENTARIO,ID_DEPARTAMENTO=ID_DEPARTAMENTO,NOMBRE="NOMBRE",DESCRIPCION="DESCRIPCION",CANTIDAD=CANTIDAD,VALOR=VALOR WHERE ID_INVENTARIO=ID_INVENTARIO;
DELETE * FROM INVENTARIO WHERE ID_INVENTARIO=ID_INVENTARIO;



-- PROCEDIMIENTOS --

CREATE OR REPLACE PROCEDURE proc_insert_inventario(v_id_inventario NUMBER,v_id_departamento NUMBER,v_nombre VARCHAR2,v_descripcion VARCHAR2,v_cantidad NUMBER,v_valor NUMBER)
AS 
BEGIN 
INSERT INTO Inventario (ID_INVENTARIO,ID_DEPARTAMENTO,NOMBRE,DESCRIPCION,CANTIDAD,VALOR) VALUES (v_id_inventario,v_id_departamento,v_nombre,v_descripcion,v_cantidad,v_valor);    
END;

