

-- Tablas de JobHistory

SELECT * FROM JOB_HISTORY WHERE EMPLOYEE_ID=EMPLOYEE_ID;
SELECT * FROM JOB_HISTORY;
INSERT INTO JOB_HISTORY (EMPLOYEE_ID,START_DATE,END_DATE,JOB_ID,DEPARTMENT_ID) VALUES (EMPLOYEE_ID,"START_DATE","END_DATE","JOB_ID",DEPARTMENT_ID);
UPDATE JOB_HISTORY SET EMPLOYEE_ID=EMPLOYEE_ID,START_DATE="START_DATE",END_DATE="END_DATE",JOB_ID="JOB_ID",DEPARTMENT_ID=DEPARTMENT_ID WHERE EMPLOYEE_ID=EMPLOYEE_ID;
DELETE * FROM JOB_HISTORY WHERE EMPLOYEE_ID=EMPLOYEE_ID;



-- PROCEDIMIENTOS --

CREATE OR REPLACE PROCEDURE proc_insert_job_history(v_employee_id NUMBER,v_start_date DATE,v_end_date DATE,v_job_id VARCHAR2,v_department_id NUMBER)
AS 
BEGIN 
INSERT INTO JobHistory (EMPLOYEE_ID,START_DATE,END_DATE,JOB_ID,DEPARTMENT_ID) VALUES (v_employee_id,v_start_date,v_end_date,v_job_id,v_department_id);    
END;

