

-- Tablas de Jobs

SELECT * FROM JOBS WHERE JOB_ID=JOB_ID;
SELECT * FROM JOBS;
INSERT INTO JOBS (JOB_ID,JOB_TITLE,MIN_SALARY,MAX_SALARY) VALUES ("JOB_ID","JOB_TITLE",MIN_SALARY,MAX_SALARY);
UPDATE JOBS SET JOB_ID="JOB_ID",JOB_TITLE="JOB_TITLE",MIN_SALARY=MIN_SALARY,MAX_SALARY=MAX_SALARY WHERE JOB_ID="JOB_ID";
DELETE * FROM JOBS WHERE JOB_ID=JOB_ID;



-- PROCEDIMIENTOS --

CREATE OR REPLACE PROCEDURE proc_insert_jobs(v_job_id VARCHAR2,v_job_title VARCHAR2,v_min_salary NUMBER,v_max_salary NUMBER)
AS 
BEGIN 
INSERT INTO Jobs (JOB_ID,JOB_TITLE,MIN_SALARY,MAX_SALARY) VALUES (v_job_id,v_job_title,v_min_salary,v_max_salary);    
END;

