

-- Tablas de Reserva

SELECT * FROM RESERVA WHERE ID_RESERVA=ID_RESERVA;
SELECT * FROM RESERVA;
INSERT INTO RESERVA (ID_RESERVA,ID_CLIENTE,ID_DEPARTAMENTO,FECHA_INICIO,FECHA_TERMINO,COSTO_TOTAL,CHECK_IN,CHECK_OUT) VALUES (ID_RESERVA,ID_CLIENTE,ID_DEPARTAMENTO,"FECHA_INICIO","FECHA_TERMINO",COSTO_TOTAL,"CHECK_IN","CHECK_OUT");
UPDATE RESERVA SET ID_RESERVA=ID_RESERVA,ID_CLIENTE=ID_CLIENTE,ID_DEPARTAMENTO=ID_DEPARTAMENTO,FECHA_INICIO="FECHA_INICIO",FECHA_TERMINO="FECHA_TERMINO",COSTO_TOTAL=COSTO_TOTAL,CHECK_IN="CHECK_IN",CHECK_OUT="CHECK_OUT" WHERE ID_RESERVA=ID_RESERVA;
DELETE * FROM RESERVA WHERE ID_RESERVA=ID_RESERVA;



-- PROCEDIMIENTOS --

CREATE OR REPLACE PROCEDURE proc_insert_reserva(v_id_reserva NUMBER,v_id_cliente NUMBER,v_id_departamento NUMBER,v_fecha_inicio DATE,v_fecha_termino DATE,v_costo_total NUMBER,v_check_in CHAR,v_check_out CHAR)
AS 
BEGIN 
INSERT INTO Reserva (ID_RESERVA,ID_CLIENTE,ID_DEPARTAMENTO,FECHA_INICIO,FECHA_TERMINO,COSTO_TOTAL,CHECK_IN,CHECK_OUT) VALUES (v_id_reserva,v_id_cliente,v_id_departamento,v_fecha_inicio,v_fecha_termino,v_costo_total,v_check_in,v_check_out);    
END;

