

-- Tablas de Usuario

SELECT * FROM USUARIO WHERE ID_USUARIO=ID_USUARIO;
SELECT * FROM USUARIO;
INSERT INTO USUARIO (ID_USUARIO,ID_TIPO_USUARIO,ID_PERSONA,USERNAME,PASSWORD,EMAIL) VALUES (ID_USUARIO,ID_TIPO_USUARIO,ID_PERSONA,"USERNAME","PASSWORD","EMAIL");
UPDATE USUARIO SET ID_USUARIO=ID_USUARIO,ID_TIPO_USUARIO=ID_TIPO_USUARIO,ID_PERSONA=ID_PERSONA,USERNAME="USERNAME",PASSWORD="PASSWORD",EMAIL="EMAIL" WHERE ID_USUARIO=ID_USUARIO;
DELETE * FROM USUARIO WHERE ID_USUARIO=ID_USUARIO;



-- PROCEDIMIENTOS --

CREATE OR REPLACE PROCEDURE proc_insert_usuario(v_id_usuario NUMBER,v_id_tipo_usuario NUMBER,v_id_persona NUMBER,v_username VARCHAR2,v_password VARCHAR2,v_email VARCHAR2)
AS 
BEGIN 
INSERT INTO Usuario (ID_USUARIO,ID_TIPO_USUARIO,ID_PERSONA,USERNAME,PASSWORD,EMAIL) VALUES (v_id_usuario,v_id_tipo_usuario,v_id_persona,v_username,v_password,v_email);    
END;

